spring:
  application:
    name: 4vidia-front

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 386
      timeout: 5000ms

  jwt:
    secret: "qwertyujhgfdsazxcvbnjhgfdsqwertyuhgfdsazxcvb" #${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/

server:
  port: 8080

toss:
  clientKey: ${TOSS_CLIENT_KEY}
